server.error.include-message: always
server.forward-headers-strategy: framework

# Health
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

# Logging
logging.level:
    root: info
    com.rufusy: debug

app:
    eureka-server: localhost
    eureka-username: user
    eureka-password: pwd
    auth-server: localhost

# Eureka
eureka:
    client:
        service-url.defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 5

# Spring cloud stream
spring.cloud.stream.defaultBinder: rabbit

spring.rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

spring.cloud.stream.kafka.binder:
    brokers: 127.0.0.1
    defaultBrokerPort: 9092

---
spring.config.activate.on-profile: docker

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

app:
    eureka-server: eureka
    auth-server: auth-server

---
spring.config.activate.on-profile: kafka

management.health.rabbit.enabled: false
spring.cloud.stream.defaultBinder: kafka
spring.kafka.bootstrap-servers: kafka:9092
spring.cloud.stream.kafka.binder.replication-factor: 1