spring:
  application:
    name: production-service
server:
  port: 7001
  error:
    include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: info
    com.rufusy: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring:
  config.activate.on-profile: docker
  data.mongodb.host: mongodb

server.port: 8080

