spring:
  application:
    name: production-service
server:
  port: 7001
  error:
    include-message: always
logging:
  level:
    root: info
    com.rufusy: debug

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080

