spring.application.name: auth-server

server.port: 9999
server.forward-headers-strategy: framework

# Eureka
app:
  eureka-server: localhost
  eureka-username: user
  eureka-password: pwd
  auth-server-username: user
  auth-server-password: pwd

eureka:
  client:
    service-url.defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

# Health
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

# Logging
logging:
  level:
    root: info
    org.springframework.security: trace

---
spring.config.activate.on-profile: docker

app.eureka-server: eureka